name: Complex
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu-step
        run: date
  windows:
    runs-on: windows-latest
    steps:
      - name: windows-latest
        run: date
  macos:
    runs-on: macos-latest
    steps:
       - name: macos-step
         run: date
  depends: 
    needs: [ubuntu, windows, macos]
    runs-on: macos-latest
    steps:
      - name: combined
        run: date
